version: '3'
services:
  # db:
  #   image: sqlite
  #   environment:
  #     MYSQL_USER: root
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - '3316:3306'
  #   volumes:
  #     - ./db/sqlite/volumes:/var/lib/sqlite
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/desire-record

    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
